# Alembic Configuration File
# name of the database branch identified by this label
# is the initial, main development branch. This label is used
# to map migration branches to database branches. Leave at the default
# of 'main' unless you have multiple named branches.

sqlalchemy.url = driver://user:pass@localhost/dbname

# template used to generate migration file
# file_template = %%(rev)s_%%(slug)s

# sys.path path, will be prepended to sys.path if present
# prepend_sys_path = .

# timezone to use when rendering the date
# within the migration file as well as the filename.
# string value is passed to datetime.datetime.now(timezone.value)
# leave blank for localtime
# timezone =

# max length of characters to apply to the
# "slug" field
# truncate_slug_len = 40

# set to 'true' to run the environment during
# the 'revision' command, regardless of autogenerate
# revision_environment = false

# set to 'true' to allow .pyc and .pyo files without
# a source .py file to be detected as revisions in the
# versions/ directory
# sourceless = false

# logging configuration
# when set to 'true', each revision file
# is expected to contain a 'down_revision' variable.
# set to 'false' to allow revision files to omit this variable
# so that they can still be executed, they just won't support direct downgrades.
# depends_on_current = false

# determines how character encoding is handled.  one of 'strict', 'utf8', or 'unicode'
# strict mode will raise an error if the target database must coerce the value via
# implicit unicode conversion (python 3 /  pep 3131). utf8 mode will decode the value
# into a unicode string, and unicode mode will configure the unicode error
# handler to coerce into a unicode string.
# sqlalchemy_track_modifications = false

sqlalchemy_echo = true

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
